name: pigeon_runner
description: A sample command-line application.
version: 1.0.0

executables:
  pigeon_runner:

environment:
  sdk: ^3.8.1

dependencies:
  path: ^1.9.1
  yaml: ^3.1.3
  dart_zx:
    git: https://github.com/YaroCabbage/dart_zx.git

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
